// <auto-generated />
using System;
using AcessoDados.DAL.EntityCodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AcessoDados.DAL.Migrations
{
    [DbContext(typeof(CodeFirstDBContext))]
    [Migration("20210223123025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlagExcluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlagExcluido")
                        .HasColumnType("bit");

                    b.Property<int>("Nome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsavel");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlagExcluido")
                        .HasColumnType("bit");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMinima")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdVideo");

                    b.HasIndex("IdResponsavel");

                    b.HasIndex("IdadeMinima")
                        .HasDatabaseName("IX_VIDEO_IDADE");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.VideoCategoria", b =>
                {
                    b.Property<int>("IdVideoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FlagExcluido")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCriacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdVideoCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdVideo");

                    b.ToTable("VideoCategoria");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", b =>
                {
                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Responsavel", "Responsavel")
                        .WithMany("Videos")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.VideoCategoria", b =>
                {
                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Categoria", "Categoria")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", "Video")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Categoria", b =>
                {
                    b.Navigation("VideoCategorias");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Responsavel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("AcessoDados.DAL.EntityCodeFirst.Modelos.Video", b =>
                {
                    b.Navigation("VideoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
